declare const routines = {
  MONDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "06:00", activity: "Morning Exercise" },
    { time: "07:00", activity: "Breakfast" },
    { time: "09:00", activity: "Work/Study" },
    { time: "12:00", activity: "Lunch Break" },
    { time: "13:00", activity: "Work/Study" },
    { time: "17:00", activity: "Evening Walk" },
    { time: "18:00", activity: "Dinner Preparation" },
    { time: "19:00", activity: "Family Time" },
    { time: "21:00", activity: "Relaxation/Reading" },
    { time: "22:00", activity: "Prepare for Bed" },
    { time: "23:00", activity: "Sleep" },
  ],
  TUESDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "06:00", activity: "Morning Yoga" },
    { time: "07:00", activity: "Breakfast" },
    { time: "09:00", activity: "Project Work" },
    { time: "12:00", activity: "Lunch Break" },
    { time: "13:00", activity: "Meetings" },
    { time: "16:00", activity: "Work/Study" },
    { time: "18:00", activity: "Cooking" },
    { time: "19:00", activity: "Netflix/Relaxation" },
    { time: "21:00", activity: "Reading" },
    { time: "22:00", activity: "Prepare for Bed" },
    { time: "23:00", activity: "Sleep" },
  ],
  WEDNESDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "06:30", activity: "Jogging" },
    { time: "07:30", activity: "Breakfast" },
    { time: "09:00", activity: "Work" },
    { time: "11:00", activity: "Team Sync" },
    { time: "13:00", activity: "Lunch Break" },
    { time: "14:00", activity: "Project Review" },
    { time: "17:00", activity: "Evening Stroll" },
    { time: "19:00", activity: "Family Time" },
    { time: "20:00", activity: "Dinner" },
    { time: "21:00", activity: "Relaxation" },
    { time: "23:00", activity: "Sleep" },
  ],
  THURSDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "06:00", activity: "Meditation" },
    { time: "07:00", activity: "Breakfast" },
    { time: "08:30", activity: "Work/Study" },
    { time: "12:00", activity: "Lunch Break" },
    { time: "13:00", activity: "Client Call" },
    { time: "16:00", activity: "Focus Session" },
    { time: "18:00", activity: "Cooking" },
    { time: "19:00", activity: "Relaxation/TV" },
    { time: "20:30", activity: "Dinner" },
    { time: "22:00", activity: "Prepare for Bed" },
    { time: "23:00", activity: "Sleep" },
  ],
  FRIDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "06:00", activity: "Morning Exercise" },
    { time: "07:30", activity: "Breakfast" },
    { time: "08:30", activity: "Work/Study" },
    { time: "12:00", activity: "Lunch Break" },
    { time: "14:00", activity: "Project Review" },
    { time: "17:00", activity: "Evening Walk" },
    { time: "19:00", activity: "Relaxation" },
    { time: "20:00", activity: "Dinner" },
    { time: "22:00", activity: "Netflix" },
    { time: "23:00", activity: "Sleep" },
  ],
  SATURDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "07:00", activity: "Leisure Time" },
    { time: "09:00", activity: "Brunch" },
    { time: "10:00", activity: "Shopping" },
    { time: "13:00", activity: "Lunch" },
    { time: "15:00", activity: "Relaxation/Movies" },
    { time: "18:00", activity: "Dinner Preparation" },
    { time: "19:00", activity: "Family Time" },
    { time: "21:00", activity: "Reading" },
    { time: "22:00", activity: "Prepare for Bed" },
    { time: "23:00", activity: "Sleep" },
  ],
  SUNDAY: [
    { time: "00:00", activity: "Sleep" },
    { time: "08:00", activity: "Breakfast" },
    { time: "09:00", activity: "Outdoor Activities" },
    { time: "12:00", activity: "Lunch" },
    { time: "14:00", activity: "Nap/Relaxation" },
    { time: "16:00", activity: "Hobby Time" },
    { time: "18:00", activity: "Prepare for the Week" },
    { time: "19:00", activity: "Dinner" },
    { time: "21:00", activity: "Family Time" },
    { time: "22:00", activity: "Prepare for Bed" },
    { time: "23:00", activity: "Sleep" },
  ],
};
